package skeleton

// manifestTmpl generates a valid manifest.yaml.
var manifestTmpl = `# manifest.yaml — {{ .Name }}
# Generated by ddis skeleton

ddis_version: "3.0"
spec_name: "{{ .Name }}"
tier_mode: "{{ if eq (len .Domains) 1 }}two-tier{{ else }}three-tier{{ end }}"

context_budget:
  target_lines: 4000
  hard_ceiling_lines: 5000
  reasoning_reserve: 0.25

constitution:
  system: "constitution/system.md"

modules:
{{- range $i, $d := .Domains }}
  {{ $d }}:
    file: "modules/{{ $d }}.md"
    domain: {{ $d }}
    maintains:
      - APP-INV-{{ printf "%03d" (add (add $i $i) 1) }}
      - APP-INV-{{ printf "%03d" (add (add $i $i) 2) }}
    interfaces: []
    implements:
      - APP-ADR-{{ printf "%03d" (add $i 1) }}
    adjacent: []
    deep_context: null
    negative_specs:
      - "Must NOT {{ $d }} without validation"
{{- end }}

invariant_registry:
{{- range $i, $d := .Domains }}
  APP-INV-{{ printf "%03d" (add (add $i $i) 1) }}: { owner: {{ $d }}, domain: {{ $d }}, description: "{{ upper $d }} primary invariant — TODO: define" }
  APP-INV-{{ printf "%03d" (add (add $i $i) 2) }}: { owner: {{ $d }}, domain: {{ $d }}, description: "{{ upper $d }} secondary invariant — TODO: define" }
{{- end }}
`

// constitutionTmpl generates a valid system constitution.
var constitutionTmpl = `---
module: system-constitution
domain: system
tier: 1
description: >
  System Constitution (Tier 1) — included in EVERY bundle.
  Contains executive summary, invariant/ADR/gate declarations,
  glossary, and cross-cutting concerns for {{ .Name }}.
ddis_version: "3.0"
tier_mode: {{ if eq (len .Domains) 1 }}two-tier{{ else }}three-tier{{ end }}
---

# {{ .Name }}

## Version 1.0

> Design goal: <!-- TODO: describe the design goal for {{ .Name }} -->

---

# PART 0: EXECUTIVE BLUEPRINT

## 0.1 Executive Summary

<!-- TODO: Write a 2-3 paragraph executive summary describing what {{ .Name }} does,
     its primary purpose, and its core value proposition. -->

### 0.1.1 Non-Negotiables (Engineering Contract)

<!-- TODO: List 3-5 non-negotiable properties. Each should reference an APP-INV. -->
{{- range $i, $d := .Domains }}

- **{{ upper $d }} invariant 1.** <!-- TODO: describe --> (APP-INV-{{ printf "%03d" (add (add $i $i) 1) }})

- **{{ upper $d }} invariant 2.** <!-- TODO: describe --> (APP-INV-{{ printf "%03d" (add (add $i $i) 2) }})
{{- end }}

---

## 0.3 Invariant Registry (Declarations)

<!-- All application invariants. Full definitions with formal expressions,
     violation scenarios, and validation methods are in the owning module. -->
{{- range $i, $d := .Domains }}

**APP-INV-{{ printf "%03d" (add (add $i $i) 1) }}: {{ upper $d }} Primary Invariant** (Owner: {{ $d }})
<!-- TODO: One-line description of this invariant -->
Confidence: falsified
*Violation: <!-- TODO: describe a concrete violation scenario -->*

**APP-INV-{{ printf "%03d" (add (add $i $i) 2) }}: {{ upper $d }} Secondary Invariant** (Owner: {{ $d }})
<!-- TODO: One-line description of this invariant -->
Confidence: falsified
*Violation: <!-- TODO: describe a concrete violation scenario -->*
{{- end }}

---

## 0.5 ADR Registry (Declarations)

<!-- All architecture decision records. Full specifications with Problem, Options,
     Decision, WHY NOT, Consequences, and Tests are in the implementing module. -->
{{- range $i, $d := .Domains }}

**APP-ADR-{{ printf "%03d" (add $i 1) }}: {{ upper $d }} Architecture Decision** (Implements: {{ $d }})
Decision: <!-- TODO: describe the decision -->
WHY NOT alternative: <!-- TODO: explain why the alternative was rejected -->
{{- end }}

---

## 0.6 Quality Gates (Declarations)

| Gate | Name | Validates | Check Type |
|------|------|-----------|------------|
| Gate-1 | Structural Conformance | All commands accept expected inputs | Mechanical |
| Gate-2 | Causal Chain | Commands trace through APP-ADR/INV | Sampling |
| Gate-3 | Decision Coverage | All choices have APP-ADRs | Review |
| Gate-4 | Invariant Falsifiability | Each APP-INV has violation + test | Constructive |
| Gate-5 | Cross-Reference Web | No orphan sections | Graph analysis |
| Gate-6 | Self-Validation | Spec validates itself | Mechanical |

**Gate 1: Structural Conformance**
All commands accept expected inputs and produce expected output shapes. Tested mechanically.

**Gate 2: Causal Chain**
Every command traces through an APP-ADR or APP-INV to the formal state model. Verified by sampling.

**Gate 3: Decision Coverage**
All design choices have corresponding APP-ADRs. Verified by review.

**Gate 4: Invariant Falsifiability**
Each APP-INV has a concrete violation scenario and at least one test. Verified constructively.

**Gate 5: Cross-Reference Web**
No orphan sections in the specification. Verified by graph analysis.

**Gate 6: Self-Validation**
The specification validates itself with zero errors. This is the self-bootstrapping gate.

---

## 0.7 Glossary

| Term | Definition |
|---|---|
| **Invariant** | A property that must hold at all times. Each is identified by an APP-INV code. |
| **ADR** | Architecture Decision Record. Each is identified by an APP-ADR code. |
| **Gate** | A quality checkpoint that must pass before the specification is considered complete. |
<!-- TODO: Add domain-specific terms -->

---

## 0.8 Section Map

| Section Range | Module File | Notes |
|---|---|---|
| §0.1-§0.8, APP-INV/ADR/Gate declarations, Glossary | constitution/system.md | Cross-cutting |
{{- range $i, $d := .Domains }}
| {{ upper $d }} invariants, ADRs, domain logic | modules/{{ $d }}.md | Owns APP-INV-{{ printf "%03d" (add (add $i $i) 1) }}, -{{ printf "%03d" (add (add $i $i) 2) }} |
{{- end }}
`

// moduleTmpl generates a valid module file.
var moduleTmpl = `---
module: {{ .Domain }}
domain: {{ .Domain }}
maintains: [APP-INV-{{ printf "%03d" (add (add .DomainIdx .DomainIdx) -1) }}, APP-INV-{{ printf "%03d" (add .DomainIdx .DomainIdx) }}]
interfaces: []
implements: [APP-ADR-{{ printf "%03d" .DomainIdx }}]
adjacent: []
negative_specs:
  - "Must NOT {{ .Domain }} without validation"
---

# {{ .DomainUpper }} Module

<!-- TODO: Write a paragraph describing what this module does and its architectural role. -->

---

## Invariants

This module maintains two invariants. Each invariant is fully specified with all five components: plain-language statement, semi-formal expression, violation scenario, validation method, and WHY THIS MATTERS annotation.

---

**APP-INV-{{ printf "%03d" (add (add .DomainIdx .DomainIdx) -1) }}: {{ .DomainUpper }} Primary Invariant**

*<!-- TODO: One-line plain-language statement of the invariant -->*

` + "```" + `
FOR ALL x IN {{ .Domain }}_elements:
  <!-- TODO: semi-formal expression -->
` + "```" + `

Violation scenario: <!-- TODO: describe a concrete scenario where this invariant is violated -->

Validation: <!-- TODO: describe how to mechanically verify this invariant -->

// WHY THIS MATTERS: <!-- TODO: explain the consequences of violating this invariant -->

**Confidence:** falsified

---

**APP-INV-{{ printf "%03d" (add .DomainIdx .DomainIdx) }}: {{ .DomainUpper }} Secondary Invariant**

*<!-- TODO: One-line plain-language statement of the invariant -->*

` + "```" + `
FOR ALL x IN {{ .Domain }}_elements:
  <!-- TODO: semi-formal expression -->
` + "```" + `

Violation scenario: <!-- TODO: describe a concrete scenario where this invariant is violated -->

Validation: <!-- TODO: describe how to mechanically verify this invariant -->

// WHY THIS MATTERS: <!-- TODO: explain the consequences of violating this invariant -->

**Confidence:** falsified

---

## ADRs

### APP-ADR-{{ printf "%03d" .DomainIdx }}: {{ .DomainUpper }} Architecture Decision

#### Problem

<!-- TODO: what problem does this decision solve? -->

#### Options

A) **Option A** <!-- TODO: describe option A -->
- Pros: <!-- TODO -->
- Cons: <!-- TODO -->

B) **Option B** <!-- TODO: describe option B -->
- Pros: <!-- TODO -->
- Cons: <!-- TODO -->

#### Decision

**Option A: Description.** <!-- TODO: which option and why -->

WHY NOT Option B: <!-- TODO: why the rejected option was rejected -->

#### Consequences

- <!-- TODO: list consequences -->

#### Tests

<!-- TODO: how to verify this decision holds -->

---

## Negative Specifications

**DO NOT** {{ .Domain }} without proper validation. Every operation must be verified before state transitions. (Validates APP-INV-{{ printf "%03d" (add (add .DomainIdx .DomainIdx) -1) }})

**DO NOT** silently ignore errors in {{ .Domain }} operations. All failures must be reported with actionable context. (Validates APP-INV-{{ printf "%03d" (add .DomainIdx .DomainIdx) }})

**DO NOT** allow {{ .Domain }} state to become inconsistent. If a multi-step operation fails partway, roll back all changes. (Validates APP-INV-{{ printf "%03d" (add (add .DomainIdx .DomainIdx) -1) }}, APP-INV-{{ printf "%03d" (add .DomainIdx .DomainIdx) }})
`
